### ISSUE TITLE
Banco de dados

### ISSUE THREAD

**Issue by alinecadinhoo** [alinecadinhoo/JPA-Avancado#1]
![bancodedados](https://github.com/alinecadinhoo/JPA-Avancado/assets/130421417/894800d3-0f67-4215-859a-ad57c44c5a7d)
![bancodedados1](https://github.com/alinecadinhoo/JPA-Avancado/assets/130421417/ea451f89-c926-469e-9e97-c95381aa97df)

**Comment by liazmammamdouh** [comment]
![image](https://github.com/alinecadinhoo/JPA-Avancado/assets/147306013/d31a9bcb-0158-446d-8958-50bd9a7fa379)
